### PR TITLE
Adjusted regex for file import

### PR DESCRIPTION
**Pull request by tapulator**
Some folks take advantage of JavaScript's ASI feature. The regex shouldn't be opinionated about one's coding style.

### CODE REVIEW

**Comment by beschoenen** [comment]
With this change, the semicolon (when people use it) will be left in the resulting file. The semicolon should be made optional.

**Comment by tapulator** [comment]
You're right.  :)

**Comment by beschoenen** [comment]
Thanks

**Comment by beschoenen** [comment]
I just published the update.

**Pull request merged**
